### ISSUE TITLE
 Logging, stats and record keeping

### ISSUE THREAD

**Issue by atisharma** [atisharma/Space-mining-poker#5]
We need to record (in a nice, machine readable format, perhaps json) the public and private data at each turn, for statistical analysis and bot design.

**Comment by abgandar** [comment]
#10 adds the option of a (not very machine readable) statistics file for each player listing each event/action taken.
This is incomplete for full bot design/analysis

**Comment by atisharma** [comment]
Improved to standard json format, should be machine readable by chomping line-by-line.
